---
title: "OECDactuals"
author: "Rike"
date: "2024-04-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars, echo =FALSE}
library(here)
library(data.table)
library(ggplot2)
library(MetBrewer)
library(patchwork)

devtools::load_all()

.d <- `[`
```

##

```{r pressure, echo=FALSE}
oecdbv <- fread(here("scores", "alt_scores", "oecd_bvar_ci_scores.csv"))|>
  .d(model == "bvar_qu")|>
  .d(,truth := "oecd") |>
  .d(, c("model", "country", "target", "horizon", "truth", "interval_score"))
oecdimf <- fread(here("scores", "alt_scores", "oecd_ci_scores_pava.csv"))|>
  .d(model == "IMF")|>
  .d(,truth := "oecd") |>
  .d(, c("model", "country", "target", "horizon", "truth", "interval_score")) |>
  rbind(oecdbv) |>
  dcast(country + target + horizon + truth ~ model, value.var = "interval_score")

imfbv <- fread(here("scores", "alt_scores", "imf_bvar_ci_scores.csv")) |>
  .d(model == "bvar_qu")|>
  .d(,truth := "imf") |>
  .d(, c("model", "country", "target", "horizon", "truth", "interval_score"))
imfimf <- fread(here("scores", "alt_scores", "imf_ci_scores_pava.csv")) |>
  .d(model == "IMF") |>
  .d(,truth := "imf") |>
  .d(, c("model", "country", "target", "horizon", "truth", "interval_score")) |>
  rbind(imfbv) |>
  dcast(country + target + horizon + truth ~ model, value.var = "interval_score") |>
  rbind(oecdimf) 

```


```{r, echo = FALSE}
allscores <- imfimf |>
  .d(, relwis := IMF/bvar_qu) |>
  dcast(country + target + horizon ~ truth, value.var = "relwis") |>
  .d(,horizon := factor(horizon, levels = c(0, 0.5, 1, 1.5), labels = 
                         c("Fall, same year", "Spring, same year",
                           "Fall, next year", "Spring, next year")))


ggplot(aes(x = imf, y = oecd, color = as.factor(horizon)), data = allscores) +
  geom_point() +
  geom_hline(aes(yintercept = 1)) +
  geom_vline(aes(xintercept = 1)) +
  scale_color_met_d("VanGogh2") +
  theme_uqimf() +
  scale_x_continuous(limits =  c(0, 5)) +
  ylab("OECD truth") +
  xlab("IMF truth")
  


```

\newpage

# Two BVAR specifications

```{r loaddata, echo = FALSE}
scores <- fread(here("scores", "ci_scores.csv"))

wis_scores <- fread(here("scores", "ci_scores_avgcnt.csv")) |>
  data.table::copy() |>
  .d(, .(model, error_method, method, target, horizon, interval_score, dispersion, underprediction, overprediction)) |>
  setnames("model", "source") 

crps_scores <- fread(here("scores", "sample_scores.csv")) 

#join score sets
all_scores <- 
  crps_scores[wis_scores, on = c("source", "error_method", "method", "target", "horizon")]|>
  .d(error_method == "absolute") |>
  .d(, error_method := NULL)

########

bvar_wis_scores <- fread(here("scores", "bvar_ci_scores_avgcnt.csv")) |>
  data.table::copy() |>
  .d(, .(model, target, horizon, interval_score, dispersion, underprediction, overprediction)) |>
  .d(,model := ifelse(model == "bvar_qu", "bvar_qu", "bvar_ciss")) |>
  setnames("model", "source") |>
  .d(,error_method := "directional") |>
  .d(,method := "rolling window") #change later


bvar_wis_scores <- rbind(bvar_wis_scores, bvar_wis_scores |> copy() |> .d(, error_method := "absolute"))

```



## Inflation

```{r overall_assessment_ew, fig.dim=c(12,12), echo = FALSE, warning = FALSE}

scores_cvgshort <- fread(here("scores", "ci_scores_avgcnt.csv")) |>
  setnames("model", "source", skip_absent = TRUE)


bvar_scores_cvgshort <- fread(here("scores", "bvar_ci_scores_avgcnt.csv")) |>
  setnames("model", "source", skip_absent = TRUE) |>
  .d(, source := ifelse(source == "bvar_qu", "bvar_qu", "bvar_ciss")) |>
  .d(, method := "rolling window") |>
  .d(, error_method := "absolute")


bvar_scores_cvgshort <- rbind(bvar_scores_cvgshort, bvar_scores_cvgshort |> copy() |> .d(, error_method := "directional"))


point_scores <- data.table::fread(here("scores", "pointfc_scores.csv")) 

wis_scores <- rbind(wis_scores, bvar_wis_scores) |>
    .d(source %in% c("IMF", "bvar_qu", "bvar_ciss"))
scores_cvgshort <- rbind(scores_cvgshort, bvar_scores_cvgshort)|>
    .d(source %in% c("imf", "bvar_qu", "bvar_ciss"))

ovr_assessment_plot <- function(wis_scoredat, cvg_scoredat, point_scores, crps_scores, trgt, window_method){

  cvgscores <- cvg_scoredat |>
    .d(method == window_method) |>
    .d(target == trgt) |>
    .d(, target := NULL) |>
    .d(, method := NULL) 
  
  
  decomp_data <- wis_scoredat |>
    .d(method == window_method) |>
    .d(, method := NULL)  
  
  xmax <- max(decomp_data |> copy() |> .d(target == trgt) |> .d(, .(interval_score))) + 0.01
  
  point_scores <- point_scores |>
    .d(target == trgt) |>
    .d(, target := NULL) |>
    .d(, meanae := mean(ae), by = c("source", "horizon")) |>
    .d(, meansque := mean(sque), by = c("source", "horizon")) |>
    .d(, .(source, country, horizon, meanae, meansque)) |>
    unique()
  
  crps_scores_rw <- crps_scores |>
    .d(method == window_method) |>
    .d(target == trgt) |>
    .d(, target := NULL)
  
  crps_scores_loo <- crps_scores |>
    .d(method == "leave-one-out") |>
    .d(target == trgt) |>
    .d(, target := NULL)
  
  
  dir_wis_plot <- wis_plot_new(decomp_data |> .d(error_method  == "directional"), trgt, xmax = xmax, plot_name = "WIS - Directional Errors", metcolor = "VanGogh2")
  abs_wis_plot <- wis_plot_new(decomp_data |> .d(error_method  == "absolute"), trgt, xmax = xmax, plot_name = "WIS - Absolute Errors")
  
  c50plot <- horizon_path_plot(cvgscores, "coverage_50", "CI Coverage - 50", facet = "error_method", title = "Central Interval Coverage - alpha = 50") +
    geom_hline(aes(yintercept = 0.5)) +
    scale_y_continuous(labels = paste0(seq(0, 100, by = 25), "%"),
                       breaks = seq(0,1, by = 0.25),
                       limits = c(0,1)) 
  
  c80plot <- horizon_path_plot(cvgscores, "coverage_80", "CI Coverage - 80", facet = "error_method", title = "Central Interval Coverage - alpha = 80") +
    geom_hline(aes(yintercept = 0.8)) +
    scale_y_continuous(labels = paste0(seq(0, 100, by = 25), "%"),
                       breaks = seq(0,1, by = 0.25),
                       limits = c(0,1)) 
  
  erow <-  ggplot() + theme_void()
  
  
  aeplot <- horizon_path_plot(point_scores |> .d(, error_method := "directional"), "meanae", "Absolute Error", title = "Point Forecast - Abs. Error")
  
  squeplot <- horizon_path_plot(point_scores |> .d(, error_method := "directional"), "meansque", "Squared Error", title = "Point Forecast - Squ. Error")
  
  crpsplot_rw <- horizon_path_plot(crps_scores_rw |>.d(, error_method := "directional"), "score", "CRPS by Sample", title = paste0("CRPS - ", window_method)) +
    scale_y_continuous(limits = c(0.07,1.05)) 
  
  
  crpsplot_loo <- horizon_path_plot(crps_scores_loo |>.d(, error_method := "directional"), "score", "CRPS by Sample", title = "CRPS - LOO") +
    scale_y_continuous(limits = c(0.07,1.05)) 
  
  
  
  ovr_plot <- 
    (abs_wis_plot) +
    plot_layout(guides = "collect", 
                heights = c(0.2, 0.05, 0.2, 0.05, 0.2)) &
      plot_annotation(tag_levels = 'I')  &
      theme(legend.position = 'bottom', 
            legend.box="vertical", legend.margin=margin()) 


  
  return(ovr_plot)
}

ovr_assessment_plot(wis_scores, scores_cvgshort, point_scores, all_scores, trgt = "pcpi_pch", window_method = "rolling window")
   

```
## GDP

```{r gdpovr_rw, echo = FALSE, warning = TRUE, fig.dim=c(12,12), warning = FALSE}

ovr_assessment_plot(wis_scores, scores_cvgshort, point_scores, all_scores, "ngdp_rpch", window_method = "rolling window")
```

## Histogram 

```{r}
bvar_twospec <- fread(here("scores", "bvar_ci_scores.csv")) |>
  .d(model %in% c("bvar_qu", "bvar_ciss")) |>
  dcast(target + horizon  + country ~ model, value.var = "interval_score") |>
  .d(!is.na(bvar_ciss)) |> # no data for CAN, JPN 
  .d(, relwis := bvar_ciss/bvar_qu)


ggplot(aes(x = relwis), data = bvar_twospec) +
  geom_histogram(binwidth = 0.13345, color = "steelblue4", fill = "steelblue3") +
  theme_uqimf() +
  xlab("Relative WIS (Reg.BVAR/CISS.BVAR)")
```

