---
title: "Length of Central Intervals"
author: "Rike"
date: "2023-09-08"
output: pdf_document
---


```{r setup, include=FALSE}
library(data.table)
library(here)
library(ggplot2)
library(patchwork)
library(MetBrewer)
library(purrr)
library(lattice)
library(gt)
library(rlang)
library(tidyverse)
devtools::load_all()
knitr::opts_chunk$set(echo = TRUE)
.d <- `[`
```

```{r loaddata}
fcdat <- data.table::fread(here("quantile_forecasts", "quantile_forecasts.csv")) 
```

## Investigate width of intervals


```{r width, echo=FALSE}
ci_width <- fcdat |>
  .d(quantile %in% c(0.1, 0.25, 0.75, 0.9)) |>
  .d(, .(country, target, horizon, quantile, error_prediction, source, error_method, method, target_year)) |>
  .d(,quantile := paste0("q", quantile)) |>
  dcast(country + target + horizon + source + error_method + method + target_year ~ quantile, value.var = "error_prediction") |>
  .d(, width5 := q0.75 - q0.25) |>
  .d(, width8 := q0.9 - q0.1) |>
  #.d(, med := median(width), by = .(country, target, horizon, source, error_method, method)) |>
  .d(, .(country, target, horizon, source, error_method, method, width5,width8, target_year)) |>
  unique() |>
  dcast(country + target+ horizon + source + method + target_year ~ error_method, 
        value.var = c("width8", "width5")) |>
  .d(, is_longer0.8 := width8_absolute  > width8_directional) |>
  .d(, is_longer0.5 := width5_absolute  > width5_directional)
```

In `r round(mean(ci_width$is_longer0.5), 2)` of cases, the 50% prediction interval is longer for the absolute error method. 
In `r round(mean(ci_width$is_longer0.8), 2)` of cases, the 80% prediction interval is longer for the absolute error method. 
